// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB399U8edIQsXQMqPkHt-5jG-FcFDAMC8E',
    appId: '1:897807971743:web:bf4528df35790b8d3079aa',
    messagingSenderId: '897807971743',
    projectId: 'final-lab-project-219',
    authDomain: 'final-lab-project-219.firebaseapp.com',
    storageBucket: 'final-lab-project-219.firebasestorage.app',
    measurementId: 'G-NK92L9160N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB3FWcDNEK2c2HhNRRZsFFiEqtH3P82ow',
    appId: '1:897807971743:android:f6623caae8ba1f2d3079aa',
    messagingSenderId: '897807971743',
    projectId: 'final-lab-project-219',
    storageBucket: 'final-lab-project-219.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCETPFVlugueTyHAPeDcNaBlS2JQ6lQVsc',
    appId: '1:897807971743:ios:6a50ea4fb27f915b3079aa',
    messagingSenderId: '897807971743',
    projectId: 'final-lab-project-219',
    storageBucket: 'final-lab-project-219.firebasestorage.app',
    iosBundleId: 'com.example.finalLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCETPFVlugueTyHAPeDcNaBlS2JQ6lQVsc',
    appId: '1:897807971743:ios:6a50ea4fb27f915b3079aa',
    messagingSenderId: '897807971743',
    projectId: 'final-lab-project-219',
    storageBucket: 'final-lab-project-219.firebasestorage.app',
    iosBundleId: 'com.example.finalLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB399U8edIQsXQMqPkHt-5jG-FcFDAMC8E',
    appId: '1:897807971743:web:4a59f298f6a396383079aa',
    messagingSenderId: '897807971743',
    projectId: 'final-lab-project-219',
    authDomain: 'final-lab-project-219.firebaseapp.com',
    storageBucket: 'final-lab-project-219.firebasestorage.app',
    measurementId: 'G-MMQX1ZFL3Q',
  );
}
